---
title: "Revisiones de los datos de cuentas nacionales, un ejercicio de visualización"
author: "Silvia Rodríguez Collazo"
date: "6 de diciembre de 2018"
output: html_document
runtime: shiny
---

# Introducción

La estimación y cálculo de los indicadores que son parte de las Cuentas Nacionales se realizan a partir de datos que provienen de distintas fuentes, censos económicos, registros administrativos, información contable, encuestas por muestreo, entre otras.

El Banco Central del Uruguay (BCU) realiza revisiones periódicas en los datos, las más importantes en cuanto a magnitud se dan en el último trimestre del año cuando se actualiza la información que se obtiene anualmente.

En el análisis de coyuntura, el momento en que se recibe la nueva información de cuentas nacionales es importante poder conformar un primer panorama de la trayectoria de las series , la nueva información incorporada por los nuevos datos y si estas novedades implican granden cambios en las series a analizar.

Se ha analizado los efectos de las revisiones tanto a nivel de las predicciones de la trayectoria futura como en las estimaciones del componente más estable de la serie, la tendencia.

En este trabajo se crea una aplicación shiny cuyo objetivo es apoyar la primer etapa de análisis de la inueva información que publica el Banco Central en oportunidad de dar a conocer las cifras del Índice de Volumen Físico de Producto, agregado y algunos de sus componentes.

La utilidad de este proyecto de aplicación debe enetenderse en el marco de un análisis de coyuntura y cuyo objetivo preliminar es permitir al analista obtener una aproximación a las novedades que trae la nueva información, enfocándose sobre todo a las revisiones en los datos.

Por otro lado un segundo objetivo es poner a disposición del ususario y del analista un conjunto de "vintages", esto es de una base de datos con las ultimas series publicadas por el BCU.Esta disponibilidad inmediata en sí misma es de gran utilidad pues no hay una base oficial de "vintages" disponibles en la web del BCU.

## Desarrollo de la aplicación

Este proyecto es una primer aproximación al desarrollo de esta aplicación. Por tanto lo que tiene que ver con un proceso repetitivo, el referido al anaálisis de los datos de los IVF del PIB sectorial no se realizarán para cada componente del producto desagregado por sector sino en esta etapa a un conjunto de sectores, agro e industria además del IVF del PIB agregado.

Se leen los datos de una base que se alimenta en cada oportunidad, esto es, aproximadamente 45 días despues de vencido el trimestre el BCU publica en la web la nueva información, en este caso la base se elabora tomando la información que se publica en el Cuadro 132t.xls, esto es las series de IVF del PIB por industrias, base 2005=100, serie armonizada.

En base a esta información se desagrega en un conjunto de archivos, uno para el IVF del PIB agregado y otros dos para cada sector. Adicionalmente se crea un archivo que calcula las tasas de crecimiento promedio anual desde el año 2010 a 2017 ( ultimo año completo del que se disponen datos) y con ello se elabora una tabla que contiene esas tasas de crecimiento para cada "vintage". El objetivo de esta taba es analizar si las revisiones han afectado las tasas de crecimiento del pasado. La relevancia que tiene esta información es que permite revisar la visión que los analistas tenían sobre el nivel de actividad económica del país en el pasado.

```{r Desarrollo,  echo=FALSE, message=FALSE, warning=FALSE}
#knitr::opts_chunk$set(echo = FALSE)


library(shiny)

ui <- fluidPage(
  titlePanel("PIB,Revisiones y Tendencia"),
  sidebarLayout(
    sidebarPanel("Consultar PIB", 
                selectInput(inputId="accion",
                            label="Elija una serie:",
                            choices= c("IVF_PIB_1T_17","IVF_PIB_2T_17","IVF_PIB_3T_17","IVF_PIB_4T_17","IVF_PIB_1T_18","IVF_PIB_2T_18")),
                checkboxInput("logs",
                               "Transformación logarítmica",
                               value=FALSE),
                checkboxInput("x13",
                               "Componente Tendencial (X13-SEATS)",
                               value=FALSE)),
        
  mainPanel(" IVF del PIB de Uruguay y sus revisiones",
            h1('Gráfico del PIB'),
      plotOutput('grafico'),
      h2('Tasas de crecimiento interanual'),
      tableOutput("tabla")
      )
  )
)

server <- function(input, output) {
  output$grafico<-renderPlot({
    pib_uy <- read.csv("pib_uy.csv", sep=";",dec=',')
    y<-pib_uy[,input$accion]
    y<-y[!is.na(y)]
    y<-ts(y,frequency=4,start=c(1997,1))
    eje_y<-input$accion
    if(input$logs) {
      y<-log(y)
      eje_y<-paste('log(',eje_y,')',sep='')
    }
        plot(y,type='l',ylab=eje_y,xlab='trimestres', sub="Fuente:Elaboración propia en base a BCU")
    if(input$x13) {
      library(seasonal)
      x13<-seas(y,transform.function='none')
      # tendencia
      lines(x13$data[,'trend'],col='red',lwd=2)
      # seasonal
      #lines(x13$data[,'seasonaladj'],col='green',lwd=2)
      legend('topleft',c('serie','tendencia'),col=c(1,2),lwd=c(1,2),bty='n')
    }
  })
  tasa_pib <- read.csv("Tasa_crecimiento.csv", sep=";",dec=',')
  output$tabla<-renderTable(
    tasa_pib, striped=FALSE,hover=FALSE, bordered=FALSE,spacing="s", width="auto",align="c", rownames=FALSE,colnames=TRUE, digits=1
  )
}
shinyApp(ui = ui, server = server)


